import { AspectRatioOption } from '../types';

export const ASPECT_RATIOS: AspectRatioOption[] = [
  {
    id: 'xpan-65-24',
    label: 'XPAN 65:24',
    ratioName: '哈苏传奇宽幅',
    value: 65 / 24, // ~2.7083
    category: 'cinema',
    description: 'Hasselblad 24×65mm 双画幅胶片全景，经典电影级超宽视野',
    isSpecial: true,
  },
  {
    id: 'cinema-239',
    label: '2.39:1',
    ratioName: '变形宽银幕',
    value: 2.39,
    category: 'cinema',
    description: 'Anamorphic Cinemascope 电影工业标准宽银幕',
  },
  {
    id: '16-9',
    label: '16:9',
    ratioName: '高清宽屏',
    value: 16 / 9,
    category: 'cinema',
    description: '数字显示器与当代影视标准比例',
  },
  {
    id: '3-2',
    label: '3:2',
    ratioName: '135 经典全画幅',
    value: 3 / 2,
    category: 'classic',
    description: '35mm 胶片与全画幅相机原生画幅比例',
  },
  {
    id: '4-3',
    label: '4:3',
    ratioName: '中画幅 645 / M43',
    value: 4 / 3,
    category: 'classic',
    description: '经典画册出版物与中画幅相机比例',
  },
  {
    id: '1-1',
    label: '1:1',
    ratioName: '哈苏 6×6 方幅',
    value: 1,
    category: 'classic',
    description: 'Hasselblad 500C 经典腰平双反方幅构图',
  },
  {
    id: '4-5',
    label: '4:5',
    ratioName: '大画幅 / 社交肖像',
    value: 4 / 5,
    category: 'vertical',
    description: '8×10 大画幅与 Instagram/小红书最佳竖屏展示',
  },
  {
    id: '6-7',
    label: '6:7',
    ratioName: 'Pentax 67 理想画幅',
    value: 6 / 7,
    category: 'classic',
    description: '宾得 67 中画幅胶片被誉为最舒服的构图黄金比例',
  },
  {
    id: '2-3',
    label: '2:3',
    ratioName: '135 经典竖幅',
    value: 2 / 3,
    category: 'vertical',
    description: '35mm 相机竖构图，经典人像与建筑',
  },
  {
    id: '3-4',
    label: '3:4',
    ratioName: '中画幅竖幅',
    value: 3 / 4,
    category: 'vertical',
    description: '优雅古典杂志封面构图',
  },
  {
    id: '9-16',
    label: '9:16',
    ratioName: '全屏竖幅',
    value: 9 / 16,
    category: 'social',
    description: '手机全屏壁纸与短视频动态比例',
  },
  {
    id: 'original',
    label: '原图',
    ratioName: '原始比例',
    value: 0, // dynamic
    category: 'classic',
    description: '保留照片本身未裁切的原生画幅',
  },
];
